### ISSUE TITLE
Add option to discard target file if assembly failed

### ISSUE THREAD

**Issue by billkendrick** [pfusik/xasm#4]
# Proposal
Provide a command-line option that discards the output (e.g., ".obx") file if the assembly failed. Currently, in the program I'm working on, I end up with a 6-byte file containing the $FF $FF header bytes, and the start/end addresses.)

# Motivation
When using "make" and a Makefile, one needs to manually remove the broken target file ("rm program.obx") before running "make" again, otherwise it will see that the file exists and not bother making it if none of the source files have been updated since (e.g., if you forgot to add a dependency to the target in the Makefile). You'll instead just receive the message "make: Nothing to be done for 'all'.".

# Alternative
Alternatively, if there's no actual use in having the broken object file remain, this could be the default behavior (and, if anyone _needs_ the broken files to remain, a "--keep..." option could be made available).

Thanks for your consideration!

**Comment by pfusik** [comment]
I'm also using GNU Make all the time. It has an option to remove the target if the rule fails (non-zero exit code). Enable it with the following line in your Makefile:

    .DELETE_ON_ERROR:

See https://github.com/pfusik/fsog/blob/master/Makefile for an example.
The GNU Make documentation says that it should be the default behavior, but it isn't for historical reasons.

That was a workaround, now for the fix. I see no reason for xasm to keep an incomplete object file. I made a change to remove it.
However, it doesn't remove the file if it didn't start writing it (e.g. error occurred on the first pass). That should be okay for Makefiles.

Thank you for your suggestion!

**Comment by peterdell** [comment]
Hi Fox,

I think it should always delete the output file. What is the purpose of keeping the old file? In my IDE I explicitly delete the output file before calling the assembler, because of plenty of problems when I didn't. And it makes error handling in scripts much easier (file not exists => error). Just my 2 ct from personal experience.

Best Regards, Peter.

**Comment by pfusik** [comment]
I agree! Fixed.
